#### CricIntel AI - Data Loading

In [1]:
import pandas as pd
import numpy as np

# Display all columns
pd.set_option("display.max_columns", None)

# Display wider tables
pd.set_option("display.width", 1000)

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [4]:
# Load datasets

matches = pd.read_csv("../../data/raw/Matches.csv")
customers = pd.read_csv("../../data/raw/Customers.csv")
ticket_sales = pd.read_csv("../../data/raw/Ticket_Sales.csv")

print("Datasets Loaded Successfully")

Datasets Loaded Successfully

In [3]:
import os

print(os.getcwd())

C:\Users\venka\OneDrive\Desktop\CricIntel-AI\analytics\notebooks

In [5]:
print("Matches Dataset Shape :", matches.shape)
print("Customers Dataset Shape :", customers.shape)
print("Ticket Sales Dataset Shape :", ticket_sales.shape)

Matches Dataset Shape : (74, 12)
Customers Dataset Shape : (12000, 15)
Ticket Sales Dataset Shape : (150000, 10)

In [6]:
print("Matches Dataset")
display(matches.head())

print("Customers Dataset")
display(customers.head())

print("Ticket Sales Dataset")
display(ticket_sales.head())

Matches Dataset

  Match_ID  Match_Date    Season Home_Team Away_Team                               Venue       City Match_Type  Stadium_Capacity  VIP_Capacity  Premium_Capacity  Economy_Capacity
0     M001  2026-03-28  IPL 2026        DC       SRH                Arun Jaitley Stadium      Delhi     League             41000          2200              9000             29800
1     M002  2026-03-29  IPL 2026        MI       RCB                    Wankhede Stadium     Mumbai     League             33000          1800              7000             24200
2     M003  2026-03-30  IPL 2026       SRH      PBKS  Rajiv Gandhi International Stadium  Hyderabad     League             55000          3000             12000             40000
3     M004  2026-03-31  IPL 2026       CSK       RCB           M. A. Chidambaram Stadium    Chennai     League             38000          2000              8000             28000
4     M005  2026-04-01  IPL 2026        GT       CSK               Narendra Modi Stadium  Ahmedabad     League            132000          6000             26000            100000

Customers Dataset

  Customer_ID First_Name Last_Name  Gender  Age Date_of_Birth       City        State Favorite_Team            Occupation  Annual_Income Loyalty_Tier                       Email       Phone Registration_Date
0      C00001       Anay      Mall    Male   20    2006-04-08     Mumbai  Maharashtra            DC        Civil Engineer         591161       Silver       anay.mall31@gmail.com  9250165258        2024-01-07
1      C00002    Nandini      Kibe  Female   21    2005-06-09     Mumbai  Maharashtra            MI       Sales Executive         407175       Bronze   nandini.kibe368@gmail.com  7687593586        2025-01-05
2      C00003      Kabir     Kohli    Male   35    1991-11-08    Kolkata  West Bengal           LSG  Chartered Accountant         911815       Bronze  kabir.kohli651@hotmail.com  7136760652        2025-04-18
3      C00004     Darpan     Ghose    Male   52    1974-11-11  Bengaluru    Karnataka            MI          Data Analyst         830776       Bronze   darpan.ghose217@gmail.com  7248611757        2025-03-14
4      C00005     Hemani      Bava  Female   28    1998-03-17     Jaipur    Rajasthan           CSK          Data Analyst         614975       Bronze  hemani.bava812@outlook.com  6535425961        2025-07-03

Ticket Sales Dataset

  Ticket_ID Customer_ID Match_ID Booking_Date Seat_Category  Ticket_Price  Quantity  Total_Amount Payment_Method Booking_Status
0   T000001      C10477     M009   2026-03-28       Economy           800         1           800            UPI      Confirmed
1   T000002      C11088     M039   2026-03-18       Premium          2000         1          2000            UPI      Confirmed
2   T000003      C03583     M029   2026-04-10       Economy           800         1           800            UPI      Confirmed
3   T000004      C08929     M002   2026-03-02       Economy           800         2          1600     Debit Card      Confirmed
4   T000005      C02616     M036   2026-03-18       Economy           800         1           800            UPI      Confirmed

In [7]:
print("Matches Dataset")
display(matches.tail())

print("Customers Dataset")
display(customers.tail())

print("Ticket Sales Dataset")
display(ticket_sales.tail())

Matches Dataset

   Match_ID  Match_Date    Season Home_Team Away_Team                      Venue       City   Match_Type  Stadium_Capacity  VIP_Capacity  Premium_Capacity  Economy_Capacity
69     M070  2026-06-05  IPL 2026       LSG        GT       BRSABV Ekana Stadium    Lucknow       League             50000          2500             10000             37500
70     M071  2026-06-06  IPL 2026        GT       CSK      Narendra Modi Stadium  Ahmedabad  Qualifier 1            132000          6000             26000            100000
71     M072  2026-06-08  IPL 2026        MI       RCB           Wankhede Stadium     Mumbai   Eliminator             33000          1800              7000             24200
72     M073  2026-06-10  IPL 2026       CSK        MI  M. A. Chidambaram Stadium    Chennai  Qualifier 2             38000          2000              8000             28000
73     M074  2026-06-12  IPL 2026        GT       CSK      Narendra Modi Stadium  Ahmedabad        Final            132000          6000             26000            100000

Customers Dataset

      Customer_ID First_Name  Last_Name  Gender  Age Date_of_Birth       City        State Favorite_Team           Occupation  Annual_Income Loyalty_Tier                          Email       Phone Registration_Date
11995      C11996     Ekanta       Bhat  Female   27    1999-03-14     Mohali       Punjab            MI      Sales Executive         630111       Bronze     ekanta.bhat458@hotmail.com  7135220184        2024-03-03
11996      C11997     Udarsh  Venkatesh    Male   48    1978-04-14      Delhi        Delhi            GT               Banker         948603       Silver  udarsh.venkatesh875@yahoo.com  8955649127        2025-05-29
11997      C11998     Oliver    Maharaj    Male   20    2006-12-11     Mumbai  Maharashtra           LSG              Student         213075       Bronze  oliver.maharaj879@hotmail.com  6136401190        2024-06-18
11998      C11999    Bhavani      Varma  Female   35    1991-09-27     Mohali       Punjab          PBKS  Government Employee        1035366       Silver   bhavani.varma184@hotmail.com  6787097776        2024-08-19
11999      C12000    Anthony       Modi    Male   43    1983-12-22  Bengaluru    Karnataka            DC         Entrepreneur        4933250       Bronze     anthony.modi42@outlook.com  6314791614        2025-11-01

Ticket Sales Dataset

       Ticket_ID Customer_ID Match_ID Booking_Date Seat_Category  Ticket_Price  Quantity  Total_Amount Payment_Method Booking_Status
149995   T149996      C06814     M052   2026-05-12       Economy           800         1           800    Net Banking      Confirmed
149996   T149997      C09140     M021   2026-03-20       Economy           800         1           800     Debit Card      Confirmed
149997   T149998      C01264     M013   2026-02-27       Economy           800         2          1600    Credit Card      Confirmed
149998   T149999      C00330     M041   2026-04-24       Premium          2000         1          2000    Credit Card      Confirmed
149999   T150000      C06076     M015   2026-02-18       Economy           800         2          1600            UPI      Confirmed

In [8]:
print("Matches Columns")
print(matches.columns.tolist())

print("\nCustomers Columns")
print(customers.columns.tolist())

print("\nTicket Sales Columns")
print(ticket_sales.columns.tolist())

Matches Columns
['Match_ID', 'Match_Date', 'Season', 'Home_Team', 'Away_Team', 'Venue', 'City', 'Match_Type', 'Stadium_Capacity', 'VIP_Capacity', 'Premium_Capacity', 'Economy_Capacity']

Customers Columns
['Customer_ID', 'First_Name', 'Last_Name', 'Gender', 'Age', 'Date_of_Birth', 'City', 'State', 'Favorite_Team', 'Occupation', 'Annual_Income', 'Loyalty_Tier', 'Email', 'Phone', 'Registration_Date']

Ticket Sales Columns
['Ticket_ID', 'Customer_ID', 'Match_ID', 'Booking_Date', 'Seat_Category', 'Ticket_Price', 'Quantity', 'Total_Amount', 'Payment_Method', 'Booking_Status']

In [9]:
print("Matches Data Types")
display(matches.dtypes)

print("\nCustomers Data Types")
display(customers.dtypes)

print("\nTicket Sales Data Types")
display(ticket_sales.dtypes)

Matches Data Types

Match_ID            object
Match_Date          object
Season              object
Home_Team           object
Away_Team           object
Venue               object
City                object
Match_Type          object
Stadium_Capacity     int64
VIP_Capacity         int64
Premium_Capacity     int64
Economy_Capacity     int64
dtype: object

Customers Data Types

Customer_ID          object
First_Name           object
Last_Name            object
Gender               object
Age                   int64
Date_of_Birth        object
City                 object
State                object
Favorite_Team        object
Occupation           object
Annual_Income         int64
Loyalty_Tier         object
Email                object
Phone                 int64
Registration_Date    object
dtype: object

Ticket Sales Data Types

Ticket_ID         object
Customer_ID       object
Match_ID          object
Booking_Date      object
Seat_Category     object
Ticket_Price       int64
Quantity           int64
Total_Amount       int64
Payment_Method    object
Booking_Status    object
dtype: object

In [10]:
print("Matches Dataset Information")
matches.info()

print("\nCustomers Dataset Information")
customers.info()

print("\nTicket Sales Dataset Information")
ticket_sales.info()

Matches Dataset Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Match_ID          74 non-null     object
 1   Match_Date        74 non-null     object
 2   Season            74 non-null     object
 3   Home_Team         74 non-null     object
 4   Away_Team         74 non-null     object
 5   Venue             74 non-null     object
 6   City              74 non-null     object
 7   Match_Type        74 non-null     object
 8   Stadium_Capacity  74 non-null     int64
 9   VIP_Capacity      74 non-null     int64
 10  Premium_Capacity  74 non-null     int64
 11  Economy_Capacity  74 non-null     int64
dtypes: int64(4), object(8)
memory usage: 7.1+ KB

Customers Dataset Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        12000 non-null  object
 1   First_Name         12000 non-null  object
 2   Last_Name          12000 non-null  object
 3   Gender             12000 non-null  object
 4   Age                12000 non-null  int64
 5   Date_of_Birth      12000 non-null  object
 6   City               12000 non-null  object
 7   State              12000 non-null  object
 8   Favorite_Team      12000 non-null  object
 9   Occupation         12000 non-null  object
 10  Annual_Income      12000 non-null  int64
 11  Loyalty_Tier       12000 non-null  object
 12  Email              12000 non-null  object
 13  Phone              12000 non-null  int64
 14  Registration_Date  12000 non-null  object
dtypes: int64(3), object(12)
memory usage: 1.4+ MB

Ticket Sales Dataset Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 10 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Ticket_ID       150000 non-null  object
 1   Customer_ID     150000 non-null  object
 2   Match_ID        150000 non-null  object
 3   Booking_Date    150000 non-null  object
 4   Seat_Category   150000 non-null  object
 5   Ticket_Price    150000 non-null  int64
 6   Quantity        150000 non-null  int64
 7   Total_Amount    150000 non-null  int64
 8   Payment_Method  150000 non-null  object
 9   Booking_Status  150000 non-null  object
dtypes: int64(3), object(7)
memory usage: 11.4+ MB

In [11]:
print("Matches Summary")
display(matches.describe(include="all"))

print("Customers Summary")
display(customers.describe(include="all"))

print("Ticket Sales Summary")
display(ticket_sales.describe(include="all"))

Matches Summary

       Match_ID  Match_Date    Season Home_Team Away_Team                   Venue    City Match_Type  Stadium_Capacity  VIP_Capacity  Premium_Capacity  Economy_Capacity
count        74          74        74        74        74                      74      74         74         74.000000     74.000000         74.000000         74.000000
unique       74          74         1        10        10                      10      10          5               NaN           NaN               NaN               NaN
top        M001  2026-03-28  IPL 2026        RR       RCB  Sawai Mansingh Stadium  Jaipur     League               NaN           NaN               NaN               NaN
freq          1           1        74         9         9                       9       9         70               NaN           NaN               NaN               NaN
mean        NaN         NaN       NaN       NaN       NaN                     NaN     NaN        NaN      51108.108108   2605.405405      10608.108108      37894.594595
std         NaN         NaN       NaN       NaN       NaN                     NaN     NaN        NaN      30263.485647   1334.052626       5942.227726      23040.648368
min         NaN         NaN       NaN       NaN       NaN                     NaN     NaN        NaN      27000.000000   1200.000000       5000.000000      20800.000000
25%         NaN         NaN       NaN       NaN       NaN                     NaN     NaN        NaN      33000.000000   1800.000000       7000.000000      24200.000000
50%         NaN         NaN       NaN       NaN       NaN                     NaN     NaN        NaN      40000.000000   2200.000000       9000.000000      28500.000000
75%         NaN         NaN       NaN       NaN       NaN                     NaN     NaN        NaN      55000.000000   3000.000000      12000.000000      40000.000000
max         NaN         NaN       NaN       NaN       NaN                     NaN     NaN        NaN     132000.000000   6000.000000      26000.000000     100000.000000

Customers Summary

       Customer_ID First_Name Last_Name Gender           Age Date_of_Birth    City        State Favorite_Team            Occupation  Annual_Income Loyalty_Tier                                Email         Phone Registration_Date
count        12000      12000     12000  12000  12000.000000         12000   12000        12000         12000                 12000   1.200000e+04        12000                                12000  1.200000e+04             12000
unique       12000        531       538      2           NaN          7617      10           10            10                    20            NaN            4                                12000           NaN               817
top         C11961     Nathan      Kala   Male           NaN    1992-02-16  Mumbai  Maharashtra           RCB  Chartered Accountant            NaN       Bronze  ekantika.krishnamurthy201@yahoo.com           NaN        2024-03-21
freq             1         47        65   7749           NaN             8    1231         1231          1715                   630            NaN         6086                                    1           NaN                29
mean           NaN        NaN       NaN    NaN     33.291000           NaN     NaN          NaN           NaN                   NaN   1.133405e+06          NaN                                  NaN  7.997119e+09               NaN
std            NaN        NaN       NaN    NaN     10.889385           NaN     NaN          NaN           NaN                   NaN   8.657516e+05          NaN                                  NaN  1.162965e+09               NaN
min            NaN        NaN       NaN    NaN     18.000000           NaN     NaN          NaN           NaN                   NaN   4.400000e+02          NaN                                  NaN  6.000117e+09               NaN
25%            NaN        NaN       NaN    NaN     24.000000           NaN     NaN          NaN           NaN                   NaN   5.980930e+05          NaN                                  NaN  6.992592e+09               NaN
50%            NaN        NaN       NaN    NaN     32.000000           NaN     NaN          NaN           NaN                   NaN   8.712695e+05          NaN                                  NaN  7.986880e+09               NaN
75%            NaN        NaN       NaN    NaN     40.000000           NaN     NaN          NaN           NaN                   NaN   1.390806e+06          NaN                                  NaN  9.020482e+09               NaN
max            NaN        NaN       NaN    NaN     60.000000           NaN     NaN          NaN           NaN                   NaN   4.998895e+06          NaN                                  NaN  9.999582e+09               NaN

Ticket Sales Summary

       Ticket_ID Customer_ID Match_ID Booking_Date Seat_Category   Ticket_Price       Quantity   Total_Amount Payment_Method Booking_Status
count     150000      150000   150000       150000        150000  150000.000000  150000.000000  150000.000000         150000         150000
unique    150000       12000       74          136             3            NaN            NaN            NaN              4              2
top      T150000      C05415     M058   2026-03-29       Economy            NaN            NaN            NaN            UPI      Confirmed
freq           1          31     2123         2087         89839            NaN            NaN            NaN          67378         142504
mean         NaN         NaN      NaN          NaN           NaN    1584.208000       1.698887    2693.573333            NaN            NaN
std          NaN         NaN      NaN          NaN           NaN    1264.255539       0.842240    2748.916491            NaN            NaN
min          NaN         NaN      NaN          NaN           NaN     800.000000       1.000000     800.000000            NaN            NaN
25%          NaN         NaN      NaN          NaN           NaN     800.000000       1.000000     800.000000            NaN            NaN
50%          NaN         NaN      NaN          NaN           NaN     800.000000       1.000000    1600.000000            NaN            NaN
75%          NaN         NaN      NaN          NaN           NaN    2000.000000       2.000000    4000.000000            NaN            NaN
max          NaN         NaN      NaN          NaN           NaN    5000.000000       4.000000   20000.000000            NaN            NaN

# Summary

In this notebook we successfully:

- Imported the required libraries
- Loaded all three datasets
- Verified dataset dimensions
- Displayed sample records
- Reviewed column names
- Examined data types
- Generated statistical summaries
- Checked memory usage

The datasets are now ready for data quality assessment in the next notebook.