In [1]:
# =============================================================================
# MODULE 1 : LOAD MASTER DATASET
# Purpose:
# Load the cleaned analytical master dataset created from the previous notebook.
# This dataset will be used to engineer business features for analytics and AI.
# =============================================================================

import pandas as pd
import numpy as np

# Display Settings
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

# Load Master Dataset
master_df = pd.read_csv("../../data/processed/cricintel_master_dataset.csv")

print("="*70)
print("MASTER DATASET LOADED SUCCESSFULLY")
print("="*70)
print(f"Rows    : {master_df.shape[0]}")
print(f"Columns : {master_df.shape[1]}")

master_df.head()

======================================================================
MASTER DATASET LOADED SUCCESSFULLY
======================================================================
Rows    : 150000
Columns : 38

,Ticket_ID,Customer_ID,Match_ID,Booking_Date,Seat_Category,Ticket_Price,Quantity,Total_Amount,Payment_Method,Booking_Status,First_Name,Last_Name,Gender,Age,Date_of_Birth,City,State,Favorite_Team,Occupation,Annual_Income,Loyalty_Tier,Email,Phone,Registration_Date,Match_Date,Season,Home_Team,Away_Team,Venue,City_Match,Match_Type,Stadium_Capacity,VIP_Capacity,Premium_Capacity,Economy_Capacity,Min_Price,Max_Price,State_City
0,T000001,C10477,M009,2026-03-28,Economy,800,1,800,UPI,Confirmed,Netra,Narang,Female,33,1993-04-02,Bengaluru,Karnataka,KKR,Nurse,329967,Bronze,netra.narang790@outlook.com,8904618696,2024-09-12,2026-04-05,IPL 2026,SRH,RR,Rajiv Gandhi International Stadium,Hyderabad,League,55000,3000,12000,40000,500,1500,Karnataka
1,T000002,C11088,M039,2026-03-18,Premium,2000,1,2000,UPI,Confirmed,Peter,Nath,Male,55,1971-11-12,Mohali,Punjab,RCB,Police Officer,467400,Silver,peter.nath759@outlook.com,7963916621,2024-06-24,2026-05-05,IPL 2026,RCB,DC,M. Chinnaswamy Stadium,Bengaluru,League,40000,2500,9000,28500,1500,3500,Punjab
2,T000003,C03583,M029,2026-04-10,Economy,800,1,800,UPI,Confirmed,Sanya,Grover,Female,19,2007-11-26,Bengaluru,Karnataka,SRH,Police Officer,516254,Silver,sanya.grover701@hotmail.com,6785351562,2025-03-04,2026-04-25,IPL 2026,KKR,SRH,Eden Gardens,Kolkata,League,68000,3500,15000,49500,500,1500,Karnataka
3,T000004,C08929,M002,2026-03-02,Economy,800,2,1600,Debit Card,Confirmed,Wriddhish,Rajagopalan,Male,36,1990-08-18,Hyderabad,Telangana,MI,Chartered Accountant,2192494,Silver,wriddhish.rajagopalan511@outlook.com,7430869547,2024-11-30,2026-03-29,IPL 2026,MI,RCB,Wankhede Stadium,Mumbai,League,33000,1800,7000,24200,500,1500,Telangana
4,T000005,C02616,M036,2026-03-18,Economy,800,1,800,UPI,Confirmed,Saumya,Tailor,Female,52,1974-10-10,Lucknow,Uttar Pradesh,RR,Police Officer,490251,Silver,saumya.tailor783@hotmail.com,7739250144,2025-01-22,2026-05-02,IPL 2026,GT,RR,Narendra Modi Stadium,Ahmedabad,League,132000,6000,26000,100000,500,1500,Uttar Pradesh

In [2]:
# =============================================================================
# MODULE 2 : DATA TYPE CONVERSION
# Purpose:
# Convert date columns from object type to datetime format so that
# calendar-based business features can be created.
# =============================================================================

# Convert Date Columns
master_df["Booking_Date"] = pd.to_datetime(master_df["Booking_Date"])
master_df["Match_Date"] = pd.to_datetime(master_df["Match_Date"])
master_df["Date_of_Birth"] = pd.to_datetime(master_df["Date_of_Birth"])
master_df["Registration_Date"] = pd.to_datetime(master_df["Registration_Date"])

print("="*70)
print("DATE CONVERSION COMPLETED")
print("="*70)

print(master_df[
    ["Booking_Date",
     "Match_Date",
     "Date_of_Birth",
     "Registration_Date"]
].dtypes)

======================================================================
DATE CONVERSION COMPLETED
======================================================================
Booking_Date         datetime64[ns]
Match_Date           datetime64[ns]
Date_of_Birth        datetime64[ns]
Registration_Date    datetime64[ns]
dtype: object

In [3]:
# =============================================================================
# MODULE 3 : DATE & TIME FEATURES
# Purpose:
# Extract calendar-based business features for demand forecasting,
# booking trend analysis and executive reporting.
# =============================================================================

# -----------------------------
# 1. Booking Lead Time
# -----------------------------
master_df["Booking_Lead_Days"] = (
    master_df["Match_Date"] - master_df["Booking_Date"]
).dt.days

# -----------------------------
# 2. Booking Month
# -----------------------------
master_df["Booking_Month"] = master_df["Booking_Date"].dt.month_name()

# -----------------------------
# 3. Booking Weekday
# -----------------------------
master_df["Booking_Day_Name"] = master_df["Booking_Date"].dt.day_name()

# -----------------------------
# 4. Match Month
# -----------------------------
master_df["Match_Month"] = master_df["Match_Date"].dt.month_name()

# -----------------------------
# 5. Match Weekday
# -----------------------------
master_df["Match_Day_Name"] = master_df["Match_Date"].dt.day_name()

# -----------------------------
# 6. Match Quarter
# -----------------------------
master_df["Match_Quarter"] = "Q" + master_df["Match_Date"].dt.quarter.astype(str)

# -----------------------------
# 7. Weekend Match Flag
# -----------------------------
master_df["Weekend_Match"] = np.where(
    master_df["Match_Date"].dt.dayofweek >= 5,
    "Yes",
    "No"
)

print("="*70)
print("DATE & TIME FEATURES CREATED")
print("="*70)

print("New Features Added:")
print([
    "Booking_Lead_Days",
    "Booking_Month",
    "Booking_Day_Name",
    "Match_Month",
    "Match_Day_Name",
    "Match_Quarter",
    "Weekend_Match"
])

master_df.head()

======================================================================
DATE & TIME FEATURES CREATED
======================================================================
New Features Added:
['Booking_Lead_Days', 'Booking_Month', 'Booking_Day_Name', 'Match_Month', 'Match_Day_Name', 'Match_Quarter', 'Weekend_Match']

,Ticket_ID,Customer_ID,Match_ID,Booking_Date,Seat_Category,Ticket_Price,Quantity,Total_Amount,Payment_Method,Booking_Status,First_Name,Last_Name,Gender,Age,Date_of_Birth,City,State,Favorite_Team,Occupation,Annual_Income,Loyalty_Tier,Email,Phone,Registration_Date,Match_Date,Season,Home_Team,Away_Team,Venue,City_Match,Match_Type,Stadium_Capacity,VIP_Capacity,Premium_Capacity,Economy_Capacity,Min_Price,Max_Price,State_City,Booking_Lead_Days,Booking_Month,Booking_Day_Name,Match_Month,Match_Day_Name,Match_Quarter,Weekend_Match
0,T000001,C10477,M009,2026-03-28,Economy,800,1,800,UPI,Confirmed,Netra,Narang,Female,33,1993-04-02,Bengaluru,Karnataka,KKR,Nurse,329967,Bronze,netra.narang790@outlook.com,8904618696,2024-09-12,2026-04-05,IPL 2026,SRH,RR,Rajiv Gandhi International Stadium,Hyderabad,League,55000,3000,12000,40000,500,1500,Karnataka,8,March,Saturday,April,Sunday,Q2,Yes
1,T000002,C11088,M039,2026-03-18,Premium,2000,1,2000,UPI,Confirmed,Peter,Nath,Male,55,1971-11-12,Mohali,Punjab,RCB,Police Officer,467400,Silver,peter.nath759@outlook.com,7963916621,2024-06-24,2026-05-05,IPL 2026,RCB,DC,M. Chinnaswamy Stadium,Bengaluru,League,40000,2500,9000,28500,1500,3500,Punjab,48,March,Wednesday,May,Tuesday,Q2,No
2,T000003,C03583,M029,2026-04-10,Economy,800,1,800,UPI,Confirmed,Sanya,Grover,Female,19,2007-11-26,Bengaluru,Karnataka,SRH,Police Officer,516254,Silver,sanya.grover701@hotmail.com,6785351562,2025-03-04,2026-04-25,IPL 2026,KKR,SRH,Eden Gardens,Kolkata,League,68000,3500,15000,49500,500,1500,Karnataka,15,April,Friday,April,Saturday,Q2,Yes
3,T000004,C08929,M002,2026-03-02,Economy,800,2,1600,Debit Card,Confirmed,Wriddhish,Rajagopalan,Male,36,1990-08-18,Hyderabad,Telangana,MI,Chartered Accountant,2192494,Silver,wriddhish.rajagopalan511@outlook.com,7430869547,2024-11-30,2026-03-29,IPL 2026,MI,RCB,Wankhede Stadium,Mumbai,League,33000,1800,7000,24200,500,1500,Telangana,27,March,Monday,March,Sunday,Q1,Yes
4,T000005,C02616,M036,2026-03-18,Economy,800,1,800,UPI,Confirmed,Saumya,Tailor,Female,52,1974-10-10,Lucknow,Uttar Pradesh,RR,Police Officer,490251,Silver,saumya.tailor783@hotmail.com,7739250144,2025-01-22,2026-05-02,IPL 2026,GT,RR,Narendra Modi Stadium,Ahmedabad,League,132000,6000,26000,100000,500,1500,Uttar Pradesh,45,March,Wednesday,May,Saturday,Q2,Yes

In [4]:
# =============================================================================
# MODULE 3 VALIDATION
# =============================================================================

new_features = [
    "Booking_Lead_Days",
    "Booking_Month",
    "Booking_Day_Name",
    "Match_Month",
    "Match_Day_Name",
    "Match_Quarter",
    "Weekend_Match"
]

master_df[new_features].describe(include="all")

        Booking_Lead_Days Booking_Month Booking_Day_Name Match_Month Match_Day_Name Match_Quarter Weekend_Match
count       150000.000000        150000           150000      150000         150000        150000        150000
unique                NaN             6                7           4              7             2             2
top                   NaN         April         Saturday         May      Wednesday            Q2            No
freq                  NaN         53422            21677       62797          22539        141891        107569
mean            30.490953           NaN              NaN         NaN            NaN           NaN           NaN
std             17.302942           NaN              NaN         NaN            NaN           NaN           NaN
min              1.000000           NaN              NaN         NaN            NaN           NaN           NaN
25%             16.000000           NaN              NaN         NaN            NaN           NaN           NaN
50%             30.000000           NaN              NaN         NaN            NaN           NaN           NaN
75%             45.000000           NaN              NaN         NaN            NaN           NaN           NaN
max             60.000000           NaN              NaN         NaN            NaN           NaN           NaN

In [6]:
# =============================================================================
# MODULE 4 : BOOKING BEHAVIOR FEATURES
# Purpose:
# Create customer booking behaviour features to analyze
# booking patterns, booking size and booking value.
# =============================================================================

# ---------------------------------------------------
# Feature 1 : Booking Window
# ---------------------------------------------------
# Classify bookings based on how early they were made.

master_df["Booking_Window"] = np.select(
    [
        master_df["Booking_Lead_Days"] >= 30,
        master_df["Booking_Lead_Days"].between(15,29),
        master_df["Booking_Lead_Days"] < 15
    ],
    [
        "Early Booking",
        "Regular Booking",
        "Last Minute"
    ],
    default="Unknown"
)

# ---------------------------------------------------
# Feature 2 : Booking Size
# ---------------------------------------------------
# Categorize bookings by ticket quantity.

master_df["Booking_Size"] = np.select(
    [
        master_df["Quantity"] == 1,
        master_df["Quantity"] == 2,
        master_df["Quantity"] >= 3
    ],
    [
        "Single",
        "Couple",
        "Group"
    ],
    default="Unknown"
)

# ---------------------------------------------------
# Feature 3 : Bulk Booking Flag
# ---------------------------------------------------
# Flag bookings with 4 or more tickets.

master_df["Bulk_Booking"] = np.where(
    master_df["Quantity"] >= 4,
    "Yes",
    "No"
)

# ---------------------------------------------------
# Feature 4 : Revenue Per Ticket
# ---------------------------------------------------
# Calculate revenue generated by each individual ticket.

master_df["Revenue_Per_Ticket"] = (
    master_df["Total_Amount"] /
    master_df["Quantity"]
)

# ---------------------------------------------------
# Feature 5 : Seat Price Position
# ---------------------------------------------------

price_ratio = (
    (master_df["Ticket_Price"] - master_df["Min_Price"])
    /
    (master_df["Max_Price"] - master_df["Min_Price"])
)

master_df["Seat_Price_Position"] = np.select(
    [
        price_ratio <= 0.33,
        price_ratio <= 0.66,
        price_ratio > 0.66
    ],
    [
        "Low Range",
        "Mid Range",
        "High Range"
    ],
    default="Unknown"
)

# ---------------------------------------------------
# Feature 6 : Booking Value
# ---------------------------------------------------

master_df["Booking_Value"] = np.select(
    [
        master_df["Total_Amount"] < 2000,
        master_df["Total_Amount"].between(2000, 5000),
        master_df["Total_Amount"] > 5000
    ],
    [
        "Low Value",
        "Medium Value",
        "High Value"
    ],
    default="Unknown"
)
print("="*70)
print("MODULE 4 COMPLETED")
print("="*70)

print("New Features Added:")

new_features = [
    "Booking_Window",
    "Booking_Size",
    "Bulk_Booking",
    "Revenue_Per_Ticket",
    "Seat_Price_Position",
    "Booking_Value"
]

for feature in new_features:
    print("✓", feature)

======================================================================
MODULE 4 COMPLETED
======================================================================
New Features Added:
✓ Booking_Window
✓ Booking_Size
✓ Bulk_Booking
✓ Revenue_Per_Ticket
✓ Seat_Price_Position
✓ Booking_Value

In [9]:
# =============================================================================
# MODULE 5 : REVENUE, PRICING & BUSINESS KPI FEATURES
# Purpose:
# Create executive-level KPIs for revenue analysis, pricing efficiency,
# and business performance reporting.
# =============================================================================

# ---------------------------------------------------
# Feature 1 : Price Utilization Percentage
# ---------------------------------------------------
# Shows how much of the allowed price range was utilized.

master_df["Price_Utilization_Percentage"] = round(
    (master_df["Ticket_Price"] / master_df["Max_Price"]) * 100,
    2
)

# ---------------------------------------------------
# Feature 2 : Revenue Category
# ---------------------------------------------------
# Categorize transactions based on total revenue.

master_df["Revenue_Category"] = np.select(
    [
        master_df["Total_Amount"] < 2000,
        master_df["Total_Amount"].between(2000,5000),
        master_df["Total_Amount"] > 5000
    ],
    [
        "Low Revenue",
        "Medium Revenue",
        "High Revenue"
    ],
    default="Unknown"
)

# ---------------------------------------------------
# Feature 3 : Premium Seat Booking
# ---------------------------------------------------
# Identify Premium and VIP bookings.

master_df["Premium_Seat_Booking"] = np.where(
    master_df["Seat_Category"].isin(["Premium","VIP"]),
    "Yes",
    "No"
)
# ---------------------------------------------------
# Feature 4: Price Range
# ---------------------------------------------------

master_df["Price_Range"] = np.select(
    [
        master_df["Ticket_Price"] <= 1000,
        master_df["Ticket_Price"].between(1001,3000),
        master_df["Ticket_Price"] > 3000
    ],
    [
        "Budget",
        "Mid Range",
        "Premium"
    ],
    default="Unknown"
)

# ---------------------------------------------------
# Feature 5 : Revenue Contribution (%)
# ---------------------------------------------------
# Contribution of each booking to overall revenue.

total_revenue = master_df["Total_Amount"].sum()

master_df["Revenue_Contribution"] = round(
    (master_df["Total_Amount"] / total_revenue) * 100,
    6
)

# ---------------------------------------------------
# Feature 6 : High Value Transaction
# ---------------------------------------------------
# Flag transactions above the 90th percentile.

threshold = master_df["Total_Amount"].quantile(0.90)

master_df["High_Value_Transaction"] = np.where(
    master_df["Total_Amount"] >= threshold,
    "Yes",
    "No"
)

print("="*70)
print("MODULE 5 COMPLETED")
print("="*70)

new_features = [
    "Price_Utilization_Percentage",
    "Revenue_Category",
    "Premium_Seat_Booking",
    "Ticket_Price_Index",
    "Revenue_Contribution",
    "High_Value_Transaction"
]

print("New Features Added:")
for feature in new_features:
    print("✓", feature)

======================================================================
MODULE 5 COMPLETED
======================================================================
New Features Added:
✓ Price_Utilization_Percentage
✓ Revenue_Category
✓ Premium_Seat_Booking
✓ Ticket_Price_Index
✓ Revenue_Contribution
✓ High_Value_Transaction

In [10]:
# =============================================================================
# MODULE 5 VALIDATION
# =============================================================================

features = [
    "Price_Utilization_Percentage",
    "Revenue_Category",
    "Premium_Seat_Booking",
    "Ticket_Price_Index",
    "Revenue_Contribution",
    "High_Value_Transaction"
]

master_df[features].describe(include="all")

,Price_Utilization_Percentage,Revenue_Category,Premium_Seat_Booking,Ticket_Price_Index,Revenue_Contribution,High_Value_Transaction
count,150000.000000,150000,150000,150000.0,150000.000000,150000
unique,NaN,3,2,NaN,NaN,2
top,NaN,Low Revenue,No,NaN,NaN,No
freq,NaN,76526,89839,NaN,NaN,128037
mean,57.502581,NaN,NaN,1.0,0.000667,NaN
std,8.821699,NaN,NaN,0.0,0.000680,NaN
min,53.330000,NaN,NaN,1.0,0.000198,NaN
25%,53.330000,NaN,NaN,1.0,0.000198,NaN
50%,53.330000,NaN,NaN,1.0,0.000396,NaN
75%,57.140000,NaN,NaN,1.0,0.000990,NaN
max,83.330000,NaN,NaN,1.0,0.004950,NaN

In [11]:
# =============================================================================
# MODULE 6 : CUSTOMER SEGMENTATION FEATURES
# Purpose:
# Segment customers based on demographics, income, loyalty,
# and match location to support customer analytics and AI.
# =============================================================================

# ---------------------------------------------------
# Feature 1 : Age Group
# ---------------------------------------------------

master_df["Age_Group"] = pd.cut(
    master_df["Age"],
    bins=[0, 18, 25, 35, 50, 100],
    labels=[
        "Under 18",
        "19-25",
        "26-35",
        "36-50",
        "50+"
    ]
)

# ---------------------------------------------------
# Feature 2 : Income Group
# ---------------------------------------------------

master_df["Income_Group"] = pd.cut(
    master_df["Annual_Income"],
    bins=[0, 500000, 1000000, 2000000, float("inf")],
    labels=[
        "Low Income",
        "Middle Income",
        "Upper Middle",
        "High Income"
    ]
)

# ---------------------------------------------------
# Feature 3 : Loyalty Score
# ---------------------------------------------------

loyalty_mapping = {
    "Bronze": 1,
    "Silver": 2,
    "Gold": 3,
    "Platinum": 4
}

master_df["Loyalty_Score"] = master_df["Loyalty_Tier"].map(loyalty_mapping)

# ---------------------------------------------------
# Feature 4 : Customer Value
# ---------------------------------------------------

master_df["Customer_Value"] = np.select(
    [
        (master_df["Loyalty_Score"] >= 3) &
        (master_df["Total_Amount"] >= 5000),

        (master_df["Loyalty_Score"] >= 2) &
        (master_df["Total_Amount"] >= 2000),

        True
    ],
    [
        "High Value",
        "Medium Value",
        "Low Value"
    ],
    default="Low Value"
)

# ---------------------------------------------------
# Feature 5 : Local Fan
# ---------------------------------------------------

master_df["Local_Fan"] = np.where(
    master_df["City"] == master_df["City_Match"],
    "Yes",
    "No"
)

print("="*70)
print("MODULE 6 COMPLETED")
print("="*70)

new_features = [
    "Age_Group",
    "Income_Group",
    "Loyalty_Score",
    "Customer_Value",
    "Local_Fan"
]

print("New Features Added:")
for feature in new_features:
    print("✓", feature)

======================================================================
MODULE 6 COMPLETED
======================================================================
New Features Added:
✓ Age_Group
✓ Income_Group
✓ Loyalty_Score
✓ Customer_Value
✓ Local_Fan

In [12]:
# =============================================================================
# MODULE 6 VALIDATION
# =============================================================================

features = [
    "Age_Group",
    "Income_Group",
    "Loyalty_Score",
    "Customer_Value",
    "Local_Fan"
]

master_df[features].describe(include="all")

       Age_Group   Income_Group  Loyalty_Score Customer_Value Local_Fan
count     150000         150000   150000.00000         150000    150000
unique         5              4            NaN              3         2
top        26-35  Middle Income            NaN      Low Value        No
freq       50821          62739            NaN         113769    134952
mean         NaN            NaN        1.74256            NaN       NaN
std          NaN            NaN        0.88935            NaN       NaN
min          NaN            NaN        1.00000            NaN       NaN
25%          NaN            NaN        1.00000            NaN       NaN
50%          NaN            NaN        1.00000            NaN       NaN
75%          NaN            NaN        2.00000            NaN       NaN
max          NaN            NaN        4.00000            NaN       NaN

In [13]:
# =============================================================================
# MODULE 7 : MATCH INTELLIGENCE & AI FEATURES
# Purpose:
# Create business intelligence features that support executive
# reporting and Gemini AI recommendations.
# =============================================================================

# ---------------------------------------------------
# Feature 1 : Match Stage
# ---------------------------------------------------
# Classify IPL matches into League or Playoffs.

master_df["Match_Stage"] = np.where(
    master_df["Match_Type"] == "League",
    "League",
    "Playoff"
)

# ---------------------------------------------------
# Feature 2 : Seat Category Rank
# ---------------------------------------------------
# Convert seat categories into numeric ranking.

seat_rank = {
    "Economy":1,
    "Premium":2,
    "VIP":3
}

master_df["Seat_Category_Rank"] = master_df["Seat_Category"].map(seat_rank)

# ---------------------------------------------------
# Feature 3 : Booking Urgency
# ---------------------------------------------------
# Categorize bookings based on planning time.

master_df["Booking_Urgency"] = np.select(
    [
        master_df["Booking_Lead_Days"] >= 30,
        master_df["Booking_Lead_Days"].between(15,29),
        master_df["Booking_Lead_Days"] < 15
    ],
    [
        "Planned",
        "Moderate",
        "Urgent"
    ],
    default="Unknown"
)

# ---------------------------------------------------
# Feature 4 : Favorite Team Playing
# ---------------------------------------------------
# Check whether customer's favorite team is playing.

master_df["Favorite_Team_Playing"] = np.where(
    (
        (master_df["Favorite_Team"] == master_df["Home_Team"]) |
        (master_df["Favorite_Team"] == master_df["Away_Team"])
    ),
    "Yes",
    "No"
)

# ---------------------------------------------------
# Feature 5 : Weekend Premium Booking
# ---------------------------------------------------
# Premium/VIP booking on weekends.

master_df["Weekend_Premium_Booking"] = np.where(
    (
        (master_df["Weekend_Match"] == "Yes") &
        (master_df["Seat_Category"].isin(["Premium","VIP"]))
    ),
    "Yes",
    "No"
)

# ---------------------------------------------------
# Feature 6 : Executive Attention
# ---------------------------------------------------
# Flag transactions that deserve management attention.

master_df["Executive_Attention"] = np.where(
    (
        (master_df["High_Value_Transaction"] == "Yes") &
        (master_df["Favorite_Team_Playing"] == "Yes")
    ),
    "High Priority",
    "Normal"
)

print("="*70)
print("MODULE 7 COMPLETED")
print("="*70)

new_features = [
    "Match_Stage",
    "Seat_Category_Rank",
    "Booking_Urgency",
    "Favorite_Team_Playing",
    "Weekend_Premium_Booking",
    "Executive_Attention"
]

print("New Features Added:")
for feature in new_features:
    print("✓", feature)

======================================================================
MODULE 7 COMPLETED
======================================================================
New Features Added:
✓ Match_Stage
✓ Seat_Category_Rank
✓ Booking_Urgency
✓ Favorite_Team_Playing
✓ Weekend_Premium_Booking
✓ Executive_Attention

In [14]:
# =============================================================================
# MODULE 7 VALIDATION
# =============================================================================

features = [
    "Match_Stage",
    "Seat_Category_Rank",
    "Booking_Urgency",
    "Favorite_Team_Playing",
    "Weekend_Premium_Booking",
    "Executive_Attention"
]

master_df[features].describe(include="all")

,Match_Stage,Seat_Category_Rank,Booking_Urgency,Favorite_Team_Playing,Weekend_Premium_Booking,Executive_Attention
count,150000,150000.000000,150000,150000,150000,150000
unique,2,NaN,3,2,2,2
top,League,NaN,Planned,No,No,Normal
freq,141728,NaN,77439,120202,133211,145604
mean,NaN,1.502047,NaN,NaN,NaN,NaN
std,NaN,0.672269,NaN,NaN,NaN,NaN
min,NaN,1.000000,NaN,NaN,NaN,NaN
25%,NaN,1.000000,NaN,NaN,NaN,NaN
50%,NaN,1.000000,NaN,NaN,NaN,NaN
75%,NaN,2.000000,NaN,NaN,NaN,NaN
max,NaN,3.000000,NaN,NaN,NaN,NaN

In [15]:
# =============================================================================
# MODULE 8 : FINAL VALIDATION & EXPORT
# Purpose:
# Validate the feature engineered dataset and export it
# for Power BI, Gemini AI and Streamlit.
# =============================================================================

print("="*80)
print("FEATURE ENGINEERING SUMMARY")
print("="*80)

print(f"Total Rows              : {master_df.shape[0]}")
print(f"Total Columns           : {master_df.shape[1]}")
print(f"Duplicate Rows          : {master_df.duplicated().sum()}")
print(f"Total Missing Values    : {master_df.isnull().sum().sum()}")

print("\n" + "="*80)
print("DATA TYPES")
print("="*80)
print(master_df.dtypes.value_counts())

print("\n" + "="*80)
print("MISSING VALUES")
print("="*80)

missing = master_df.isnull().sum()

missing = missing[missing > 0]

if len(missing) == 0:
    print("No Missing Values Found ✅")
else:
    print(missing)

print("\n" + "="*80)
print("ENGINEERED FEATURES")
print("="*80)

engineered_features = [

    # Module 3
    "Booking_Lead_Days",
    "Booking_Month",
    "Booking_Day_Name",
    "Match_Month",
    "Match_Day_Name",
    "Match_Quarter",
    "Weekend_Match",

    # Module 4
    "Booking_Window",
    "Booking_Size",
    "Bulk_Booking",
    "Revenue_Per_Ticket",
    "Seat_Price_Position",
    "Booking_Value",

    # Module 5
    "Price_Utilization_Percentage",
    "Revenue_Category",
    "Premium_Seat_Booking",
    "Revenue_Contribution",
    "High_Value_Transaction",
    "Price_Range",

    # Module 6
    "Age_Group",
    "Income_Group",
    "Loyalty_Score",
    "Customer_Value",
    "Local_Fan",

    # Module 7
    "Match_Stage",
    "Seat_Category_Rank",
    "Booking_Urgency",
    "Favorite_Team_Playing",
    "Weekend_Premium_Booking",
    "Executive_Attention"

]

print(f"Total Engineered Features : {len(engineered_features)}\n")

for i, feature in enumerate(engineered_features, start=1):
    print(f"{i:02d}. {feature}")

print("\n" + "="*80)
print("FINAL DATASET SHAPE")
print("="*80)

print(master_df.shape)

print("\nValidation Completed Successfully ✅")

================================================================================
FEATURE ENGINEERING SUMMARY
================================================================================
Total Rows              : 150000
Total Columns           : 69
Duplicate Rows          : 0
Total Missing Values    : 0

================================================================================
DATA TYPES
================================================================================
object            44
int64             15
datetime64[ns]     4
float64            4
category           1
category           1
Name: count, dtype: int64

================================================================================
MISSING VALUES
================================================================================
No Missing Values Found ✅

================================================================================
ENGINEERED FEATURES
================================================================================
Total Engineered Features : 30

01. Booking_Lead_Days
02. Booking_Month
03. Booking_Day_Name
04. Match_Month
05. Match_Day_Name
06. Match_Quarter
07. Weekend_Match
08. Booking_Window
09. Booking_Size
10. Bulk_Booking
11. Revenue_Per_Ticket
12. Seat_Price_Position
13. Booking_Value
14. Price_Utilization_Percentage
15. Revenue_Category
16. Premium_Seat_Booking
17. Revenue_Contribution
18. High_Value_Transaction
19. Price_Range
20. Age_Group
21. Income_Group
22. Loyalty_Score
23. Customer_Value
24. Local_Fan
25. Match_Stage
26. Seat_Category_Rank
27. Booking_Urgency
28. Favorite_Team_Playing
29. Weekend_Premium_Booking
30. Executive_Attention

================================================================================
FINAL DATASET SHAPE
================================================================================
(150000, 69)

Validation Completed Successfully ✅

In [16]:
master_df.to_csv(
    "../../data/processed/cricintel_feature_engineered_dataset.csv",
    index=False
)

In [17]:
master_df.to_csv(
    "../../data/processed/cricintel_analytics_dataset.csv",
    index=False
)

print("=" * 80)
print("CRICINTEL ANALYTICS DATASET SAVED SUCCESSFULLY")
print("=" * 80)
print("Location:")
print("../../data/processed/cricintel_analytics_dataset.csv")

================================================================================
CRICINTEL ANALYTICS DATASET SAVED SUCCESSFULLY
================================================================================
Location:
../../data/processed/cricintel_analytics_dataset.csv